#Default isn't latest so... yay...
image: gcc:latest

pipelines:
  default:
    - step:
        script:
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - gcc --version
          # Install CMake
          - apt-get update
          - apt-get install -y cmake 
          - mkdir build
          - cd build
          # Call the CMake.
          - cmake ..
          # Build the porject.
          - make