general:
  build_dir: ./DiningPhilosophers

machine:
  timezone:
    Europe/London
  environment:
    PATH: "/home/ubuntu/cmake-3.6.2-Linux-x86_64/bin:$PATH"

dependencies:
  cache_directories:
    - ~/cmake-3.6.2-Linux-x86_64
  override:
    - >
      if [ ! -d ~/cmake-3.6.2-Linux-x86_64 ]; then
        echo "No cache - building CMake"
        cd ~ && wget --quiet https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz && tar -xvf cmake-3.6.2-Linux-x86_64.tar.gz
      else
        echo "Cached CMake found"
      fi
   
workflows:
    version: 2
    build-test-and-deploy:
        jobs:
            - cmake --version          
            - mkdir build
            - cd build
  
            # Call the CMake.
            - cmake ..
  
            # Build the project.
            - make