name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build
      - name: test
        run: cd build && ctest
