name: C/C++ CI

on: [push, pull_request]

jobs:
  debug:
    runs-on: ubuntu-latest
      - name: Output
        run: echo $github.ref

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build
      - name: test
        run: cd build && ctest
